import {Command} from '@oclif/command'

export default class Problem002 extends Command {
  static description = `
  Each new term in the Fibonacci sequence is generated by adding the previous two terms.
  By starting with 1 and 2, the first 10 terms will be:

  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
  
  By considering the terms in the Fibonacci sequence whose values do not exceed four million,
  find the sum of the even-valued terms.
  `

  static args = [{name: 'fibonacciUpperLimit'}]

  async run() {
    const {args} = this.parse(Problem002)
    const fibonacciUpperLimit = Number(args.fibonacciUpperLimit)
    const fibonacci = this.fibonacciCreator([1, 2], fibonacciUpperLimit)
    const sum = fibonacci.filter(x => x % 2 === 0).reduce((accumulated, next) => accumulated + next)
    this.log(`Considering the fibonacci sequence that doesn't go beyond ${fibonacciUpperLimit} the sum of the even terms in the sequence is ${sum}`)
  }

  fibonacciCreator(sequence: number[], biggestNumberAllowed: number): number[] {
    const lastNumber = sequence[sequence.length - 1]
    if (lastNumber > biggestNumberAllowed) {
      return sequence.slice(0, sequence.length - 1)
    }
    const nextValue = sequence[sequence.length - 2] + lastNumber
    sequence.push(nextValue)
    return this.fibonacciCreator(sequence, biggestNumberAllowed)
  }
}
